"""Git operations — automated commit and push for validated code changes."""

import shutil
from pathlib import Path

import structlog
from git import Repo

from engine.config import EngineSettings, settings
from engine.context import EvolutionContext
from engine.models.evolution import DeploymentResult

logger = structlog.get_logger()


class GitDeployer:
    """Handles git operations for deploying validated code to the repository."""

    def __init__(self, config: EngineSettings | None = None) -> None:
        self.config = config or settings

    async def deploy(self, context: EvolutionContext) -> DeploymentResult:
        """Apply generated files to the managed app repo, commit, and push.

        Steps:
        1. Copy validated files from workspace to managed_app/
        2. Create a feature branch
        3. Stage and commit changes
        4. Push to remote
        """
        managed_app_path = Path(self.config.managed_app_path).resolve()
        workspace = Path(self.config.workspace_path) / context.request_id

        if not workspace.exists():
            return DeploymentResult(
                success=False,
                message=f"Workspace not found: {workspace}",
            )

        try:
            repo = Repo(managed_app_path.parent)  # Root repo containing managed_app/
        except Exception as exc:
            return DeploymentResult(
                success=False,
                message=f"Git repository not found: {exc}",
            )

        # Create feature branch
        branch_name = f"{self.config.git_branch_prefix}/{context.request_id[:8]}"
        try:
            repo.git.checkout("-b", branch_name)
            logger.info("git.branch_created", branch=branch_name)
        except Exception as exc:
            logger.warning("git.branch_exists", branch=branch_name, error=str(exc))

        # Copy generated files to managed_app/
        for gen_file in context.generated_files:
            src = workspace / gen_file.file_path
            dst = managed_app_path / gen_file.file_path

            if gen_file.action == "delete":
                dst.unlink(missing_ok=True)
                logger.debug("git.file_deleted", path=gen_file.file_path)
            elif src.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
                logger.debug("git.file_copied", path=gen_file.file_path)

        # Stage and commit
        repo.git.add("managed_app/")

        summary = context.plan.summary if context.plan else "Autonomous evolution"
        commit_message = (
            f"feat(evolution): {summary}\n\n"
            f"Request ID: {context.request_id}\n"
            f"Files changed: {len(context.generated_files)}\n"
            f"Risk score: {context.validation_result.risk_score if context.validation_result else 'N/A'}\n\n"
            f"Generated by Self-Evolving Software Engine"
        )

        commit = repo.index.commit(commit_message)
        logger.info("git.committed", sha=commit.hexsha[:8], branch=branch_name)

        # Push to remote
        try:
            origin = repo.remote("origin")
            origin.push(branch_name)
            logger.info("git.pushed", branch=branch_name)
        except Exception as exc:
            logger.warning("git.push_failed", error=str(exc))
            return DeploymentResult(
                success=True,  # Commit succeeded even if push failed
                commit_sha=commit.hexsha,
                branch=branch_name,
                message=f"Committed locally but push failed: {exc}",
            )

        return DeploymentResult(
            success=True,
            commit_sha=commit.hexsha,
            branch=branch_name,
            message=f"Successfully deployed to {branch_name}",
        )
