"""Tests for deploy-time runtime contract smoke checks."""

import httpx
import pytest
from pathlib import Path
from git import Repo

import engine.deployer.git_ops as git_ops_module
from engine.config import EngineSettings
from engine.deployer.git_ops import LocalDeployer


def _write_example_app(root: Path) -> Path:
    app_dir = root / "frontend" / "src" / "apps" / "example-app"
    app_dir.mkdir(parents=True)
    (app_dir / "index.tsx").write_text("export default function App() { return null; }")
    contracts_path = root / "contracts.yaml"
    contracts_path.write_text(
        """
apps:
  example-app:
    probes:
      - method: GET
        path: /api/v1/example-app/summary
        description: Example App summary endpoint
        required_json_fields:
          - total_items
          - regions
      - method: POST
        path: /api/v1/example-app/items/search
        description: Example App item search endpoint
        json_body:
          page: 1
          page_size: 25
          filters:
            search_query: smoke-test
        required_json_fields:
          - items
          - total
          - page
          - page_size
        required_list_fields:
          - items
""".strip(),
        encoding="utf-8",
    )
    return contracts_path


def _init_test_repo(root: Path) -> Repo:
    repo = Repo.init(root)
    with repo.config_writer() as config:
        config.set_value("user", "name", "Codex Test")
        config.set_value("user", "email", "codex@example.com")
    return repo


def test_restore_runtime_artifacts_cleans_generated_files(tmp_path):
    """Generated bytecode and engine state should never pollute evolved-app commits."""
    repo = _init_test_repo(tmp_path)
    deployer = LocalDeployer(EngineSettings(evolved_app_path=tmp_path))

    source_file = tmp_path / "backend" / "app" / "api" / "v1" / "competitive_intelligence.py"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("router = None\n", encoding="utf-8")

    tracked_pyc = (
        tmp_path
        / "backend"
        / "app"
        / "api"
        / "v1"
        / "__pycache__"
        / "competitive_intelligence.cpython-311.pyc"
    )
    tracked_pyc.parent.mkdir(parents=True)
    tracked_pyc.write_bytes(b"tracked-pyc")

    usage_file = tmp_path / ".engine-state" / "usage.json"
    usage_file.parent.mkdir(parents=True)
    usage_file.write_text('{"llm_calls": 1}\n', encoding="utf-8")

    repo.git.add("-A")
    repo.index.commit("initial")

    tracked_pyc.write_bytes(b"dirty-pyc")
    usage_file.write_text('{"llm_calls": 99}\n', encoding="utf-8")

    untracked_pyc = (
        tmp_path
        / "backend"
        / "app"
        / "models"
        / "__pycache__"
        / "company.cpython-311.pyc"
    )
    untracked_pyc.parent.mkdir(parents=True)
    untracked_pyc.write_bytes(b"temp-pyc")

    deployer._restore_runtime_artifacts(repo)

    assert tracked_pyc.read_bytes() == b"tracked-pyc"
    assert usage_file.read_text(encoding="utf-8") == '{"llm_calls": 1}\n'
    assert not untracked_pyc.exists()
    assert repo.is_dirty(untracked_files=True) is False


def test_rollback_restores_runtime_artifacts_before_revert(tmp_path):
    """Rollback should succeed even when runtime artifacts changed after a failed rebuild."""
    repo = _init_test_repo(tmp_path)
    deployer = LocalDeployer(EngineSettings(evolved_app_path=tmp_path))

    source_file = tmp_path / "backend" / "app" / "api" / "v1" / "competitive_intelligence.py"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("value = 1\n", encoding="utf-8")

    tracked_pyc = (
        tmp_path
        / "backend"
        / "app"
        / "api"
        / "v1"
        / "__pycache__"
        / "competitive_intelligence.cpython-311.pyc"
    )
    tracked_pyc.parent.mkdir(parents=True)
    tracked_pyc.write_bytes(b"tracked-pyc")

    repo.git.add("-A")
    repo.index.commit("initial")

    source_file.write_text("value = 2\n", encoding="utf-8")
    repo.git.add("-A")
    repo.index.commit("bad deploy")

    tracked_pyc.write_bytes(b"dirty-pyc")

    assert deployer._rollback(repo) is True
    assert "Revert" in repo.head.commit.message
    assert repo.is_dirty(untracked_files=True) is False


def test_increment_deploy_version_reads_typed_assignment(tmp_path):
    """Deploy version bumps should preserve and increment typed assignments."""
    deployer = LocalDeployer(EngineSettings(evolved_app_path=tmp_path))
    version_file = tmp_path / "backend" / "app" / "_deploy_version.py"
    version_file.parent.mkdir(parents=True)
    version_file.write_text("DEPLOY_VERSION: int = 7\n", encoding="utf-8")

    new_version = deployer._increment_deploy_version(tmp_path)

    assert new_version == 8
    assert "DEPLOY_VERSION: int = 8" in version_file.read_text(encoding="utf-8")


def test_sync_framework_core_files_restores_protected_backend_routes(tmp_path):
    """Framework-owned core backend files should overwrite drift in evolved-app."""
    repo_root = tmp_path / "repo"
    managed_app_root = repo_root / "managed_app"
    evolved_root = tmp_path / "evolved-app"
    managed_file = managed_app_root / "backend" / "app" / "api" / "v1" / "apps.py"
    evolved_file = evolved_root / "backend" / "app" / "api" / "v1" / "apps.py"
    manifest = repo_root / "protected_framework_files.txt"

    managed_file.parent.mkdir(parents=True, exist_ok=True)
    evolved_file.parent.mkdir(parents=True, exist_ok=True)
    managed_file.write_text("router = 'framework'\n", encoding="utf-8")
    evolved_file.write_text("router = 'drifted'\n", encoding="utf-8")
    manifest.write_text("backend/app/api/v1/apps.py\n", encoding="utf-8")

    deployer = LocalDeployer(
        EngineSettings(
            repo_root=repo_root,
            evolved_app_path=evolved_root,
        )
    )

    original_manifest = git_ops_module._PROTECTED_FRAMEWORK_FILES_PATH
    git_ops_module._PROTECTED_FRAMEWORK_FILES_PATH = manifest
    try:
        copied = deployer._sync_framework_core_files(evolved_root)
    finally:
        git_ops_module._PROTECTED_FRAMEWORK_FILES_PATH = original_manifest

    assert copied == 1
    assert evolved_file.read_text(encoding="utf-8") == "router = 'framework'\n"


def test_protected_framework_manifest_covers_runtime_support_modules():
    """Critical backend support modules must stay protected alongside the routers."""
    manifest = (
        Path(__file__).resolve().parents[2] / "protected_framework_files.txt"
    ).read_text(encoding="utf-8")
    entries = {line.strip() for line in manifest.splitlines() if line.strip()}

    assert {
        "backend/app/main.py",
        "backend/app/auth.py",
        "backend/app/system_settings.py",
        "backend/app/api/v1/auth.py",
        "backend/app/api/v1/apps.py",
        "backend/app/api/v1/settings.py",
        "backend/app/models/apps.py",
        "backend/app/models/system_settings.py",
        "backend/app/schemas/apps.py",
        "backend/app/schemas/system_settings.py",
    }.issubset(entries)


@pytest.mark.asyncio
async def test_runtime_contract_smoke_checks_pass_when_probes_match(tmp_path, monkeypatch):
    """Deploy smoke checks should accept healthy mounted app contracts."""
    contracts_path = _write_example_app(tmp_path)
    deployer = LocalDeployer(
        EngineSettings(
            evolved_app_path=tmp_path,
            monitor_url="http://backend:8000",
            runtime_contracts_path=contracts_path,
        )
    )

    async def handler(request: httpx.Request) -> httpx.Response:
        assert request.headers.get("x-ses-probe") == "runtime-contract"
        if request.method == "GET" and request.url.path == "/api/v1/health":
            return httpx.Response(200, json={"status": "ok"})
        if request.method == "GET" and request.url.path == "/api/v1/system/info":
            return httpx.Response(
                200,
                json={
                    "ok": True,
                    "status": "ok",
                    "timestamp": "2026-03-28T00:00:00Z",
                    "service": "backend",
                },
            )
        if request.method == "GET" and request.url.path == "/api/v1/evolution/status":
            return httpx.Response(
                200,
                json={
                    "total_evolutions": 0,
                    "active_evolutions": 0,
                    "completed_evolutions": 0,
                    "failed_evolutions": 0,
                    "current_purpose_version": 4,
                    "pending_inceptions": 0,
                    "last_evolution": None,
                },
            )
        if request.method == "GET" and request.url.path == "/api/v1/apps":
            return httpx.Response(200, json=[])
        if request.method == "POST" and request.url.path == "/api/v1/apps":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/apps/capabilities":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/chat":
            return httpx.Response(422, json={"detail": "missing messages"})
        if request.method == "GET" and request.url.path == "/api/v1/example-app/summary":
            return httpx.Response(
                200,
                json={
                    "total_items": 0,
                    "regions": [],
                },
            )
        if request.method == "POST" and request.url.path == "/api/v1/example-app/items/search":
            return httpx.Response(
                200,
                json={"items": [], "total": 0, "page": 1, "page_size": 25},
            )
        return httpx.Response(404)

    real_async_client = httpx.AsyncClient
    transport = httpx.MockTransport(handler)

    def client_factory(*args, **kwargs):
        kwargs["transport"] = transport
        return real_async_client(*args, **kwargs)

    monkeypatch.setattr(git_ops_module.httpx, "AsyncClient", client_factory)

    ok, message = await deployer._run_runtime_contract_smoke_checks()

    assert ok is True
    assert "Validated 9 runtime contract probes" in message


@pytest.mark.asyncio
async def test_runtime_contract_smoke_checks_fail_on_missing_or_wrong_method(tmp_path, monkeypatch):
    """Deploy smoke checks should fail fast on broken mounted app contracts."""
    contracts_path = _write_example_app(tmp_path)
    deployer = LocalDeployer(
        EngineSettings(
            evolved_app_path=tmp_path,
            monitor_url="http://backend:8000",
            runtime_contracts_path=contracts_path,
        )
    )

    async def handler(request: httpx.Request) -> httpx.Response:
        assert request.headers.get("x-ses-probe") == "runtime-contract"
        if request.method == "GET" and request.url.path == "/api/v1/health":
            return httpx.Response(200, json={"status": "ok"})
        if request.method == "GET" and request.url.path == "/api/v1/system/info":
            return httpx.Response(
                200,
                json={
                    "ok": True,
                    "status": "ok",
                    "timestamp": "2026-03-28T00:00:00Z",
                    "service": "backend",
                },
            )
        if request.method == "GET" and request.url.path == "/api/v1/evolution/status":
            return httpx.Response(
                200,
                json={
                    "total_evolutions": 0,
                    "active_evolutions": 0,
                    "completed_evolutions": 0,
                    "failed_evolutions": 0,
                    "current_purpose_version": 4,
                    "pending_inceptions": 0,
                    "last_evolution": None,
                },
            )
        if request.url.path == "/api/v1/apps":
            return httpx.Response(404, json={"detail": "Not Found"})
        if request.url.path == "/api/v1/apps/capabilities":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "GET" and request.url.path == "/api/v1/example-app/summary":
            return httpx.Response(404, json={"detail": "Not Found"})
        return httpx.Response(200)

    real_async_client = httpx.AsyncClient
    transport = httpx.MockTransport(handler)

    def client_factory(*args, **kwargs):
        kwargs["transport"] = transport
        return real_async_client(*args, **kwargs)

    monkeypatch.setattr(git_ops_module.httpx, "AsyncClient", client_factory)

    ok, message = await deployer._run_runtime_contract_smoke_checks()

    assert ok is False
    assert "GET /api/v1/apps -> HTTP 404" == message


@pytest.mark.asyncio
async def test_runtime_contract_smoke_checks_fail_on_shape_drift(tmp_path, monkeypatch):
    """Deploy smoke checks should reject 200 responses that drift from the JSON contract."""
    contracts_path = _write_example_app(tmp_path)
    deployer = LocalDeployer(
        EngineSettings(
            evolved_app_path=tmp_path,
            monitor_url="http://backend:8000",
            runtime_contracts_path=contracts_path,
        )
    )

    async def handler(request: httpx.Request) -> httpx.Response:
        assert request.headers.get("x-ses-probe") == "runtime-contract"
        if request.method == "GET" and request.url.path == "/api/v1/health":
            return httpx.Response(200, json={"status": "ok"})
        if request.method == "GET" and request.url.path == "/api/v1/system/info":
            return httpx.Response(
                200,
                json={
                    "ok": True,
                    "status": "ok",
                    "timestamp": "2026-03-28T00:00:00Z",
                    "service": "backend",
                },
            )
        if request.method == "GET" and request.url.path == "/api/v1/evolution/status":
            return httpx.Response(
                200,
                json={
                    "total_evolutions": 0,
                    "active_evolutions": 0,
                    "completed_evolutions": 0,
                    "failed_evolutions": 0,
                    "current_purpose_version": 4,
                    "pending_inceptions": 0,
                    "last_evolution": None,
                },
            )
        if request.method == "GET" and request.url.path == "/api/v1/apps":
            return httpx.Response(200, json=[])
        if request.method == "POST" and request.url.path == "/api/v1/apps":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/apps/capabilities":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/chat":
            return httpx.Response(422, json={"detail": "missing messages"})
        if request.method == "GET" and request.url.path == "/api/v1/example-app/summary":
            return httpx.Response(
                200,
                json={
                    "total_items": 0,
                    "regions": [],
                },
            )
        if request.method == "POST" and request.url.path == "/api/v1/example-app/items/search":
            return httpx.Response(
                200,
                json={"results": [], "total": 0, "page": 1, "page_size": 25},
            )
        return httpx.Response(404)

    real_async_client = httpx.AsyncClient
    transport = httpx.MockTransport(handler)

    def client_factory(*args, **kwargs):
        kwargs["transport"] = transport
        return real_async_client(*args, **kwargs)

    monkeypatch.setattr(git_ops_module.httpx, "AsyncClient", client_factory)

    ok, message = await deployer._run_runtime_contract_smoke_checks()

    assert ok is False
    assert message == (
        "POST /api/v1/example-app/items/search -> missing JSON fields: items"
    )
