"""Tests for deploy-time runtime contract smoke checks."""

import httpx
import pytest
from pathlib import Path
from git import Repo

import engine.deployer.git_ops as git_ops_module
from engine.config import EngineSettings
from engine.deployer.git_ops import LocalDeployer


def _write_example_app(root: Path) -> Path:
    app_dir = root / "frontend" / "src" / "apps" / "example-app"
    app_dir.mkdir(parents=True)
    (app_dir / "index.tsx").write_text("export default function App() { return null; }")
    contracts_path = root / "contracts.yaml"
    contracts_path.write_text(
        """
apps:
  example-app:
    probes:
      - method: GET
        path: /api/v1/example-app/summary
        description: Example App summary endpoint
        required_json_fields:
          - total_items
          - regions
      - method: POST
        path: /api/v1/example-app/items/search
        description: Example App item search endpoint
        json_body:
          page: 1
          page_size: 25
          filters:
            search_query: smoke-test
        required_json_fields:
          - items
          - total
          - page
          - page_size
        required_list_fields:
          - items
""".strip(),
        encoding="utf-8",
    )
    return contracts_path


def _init_test_repo(root: Path) -> Repo:
    repo = Repo.init(root)
    with repo.config_writer() as config:
        config.set_value("user", "name", "Codex Test")
        config.set_value("user", "email", "codex@example.com")
    return repo


def test_restore_runtime_artifacts_cleans_generated_files(tmp_path):
    """Generated bytecode and engine state should never pollute evolved-app commits."""
    repo = _init_test_repo(tmp_path)
    deployer = LocalDeployer(EngineSettings(evolved_app_path=tmp_path))

    source_file = tmp_path / "backend" / "app" / "api" / "v1" / "competitive_intelligence.py"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("router = None\n", encoding="utf-8")

    tracked_pyc = (
        tmp_path
        / "backend"
        / "app"
        / "api"
        / "v1"
        / "__pycache__"
        / "competitive_intelligence.cpython-311.pyc"
    )
    tracked_pyc.parent.mkdir(parents=True)
    tracked_pyc.write_bytes(b"tracked-pyc")

    usage_file = tmp_path / ".engine-state" / "usage.json"
    usage_file.parent.mkdir(parents=True)
    usage_file.write_text('{"llm_calls": 1}\n', encoding="utf-8")

    repo.git.add("-A")
    repo.index.commit("initial")

    tracked_pyc.write_bytes(b"dirty-pyc")
    usage_file.write_text('{"llm_calls": 99}\n', encoding="utf-8")

    untracked_pyc = (
        tmp_path
        / "backend"
        / "app"
        / "models"
        / "__pycache__"
        / "company.cpython-311.pyc"
    )
    untracked_pyc.parent.mkdir(parents=True)
    untracked_pyc.write_bytes(b"temp-pyc")

    deployer._restore_runtime_artifacts(repo)

    assert tracked_pyc.read_bytes() == b"tracked-pyc"
    assert usage_file.read_text(encoding="utf-8") == '{"llm_calls": 1}\n'
    assert not untracked_pyc.exists()
    assert repo.is_dirty(untracked_files=True) is False


def test_rollback_restores_runtime_artifacts_before_revert(tmp_path):
    """Rollback should succeed even when runtime artifacts changed after a failed rebuild."""
    repo = _init_test_repo(tmp_path)
    deployer = LocalDeployer(EngineSettings(evolved_app_path=tmp_path))

    source_file = tmp_path / "backend" / "app" / "api" / "v1" / "competitive_intelligence.py"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("value = 1\n", encoding="utf-8")

    tracked_pyc = (
        tmp_path
        / "backend"
        / "app"
        / "api"
        / "v1"
        / "__pycache__"
        / "competitive_intelligence.cpython-311.pyc"
    )
    tracked_pyc.parent.mkdir(parents=True)
    tracked_pyc.write_bytes(b"tracked-pyc")

    repo.git.add("-A")
    repo.index.commit("initial")

    source_file.write_text("value = 2\n", encoding="utf-8")
    repo.git.add("-A")
    repo.index.commit("bad deploy")

    tracked_pyc.write_bytes(b"dirty-pyc")

    assert deployer._rollback(repo) is True
    assert "Revert" in repo.head.commit.message
    assert repo.is_dirty(untracked_files=True) is False


def test_increment_deploy_version_reads_typed_assignment(tmp_path):
    """Deploy version bumps should preserve and increment typed assignments."""
    deployer = LocalDeployer(EngineSettings(evolved_app_path=tmp_path))
    version_file = tmp_path / "backend" / "app" / "_deploy_version.py"
    version_file.parent.mkdir(parents=True)
    version_file.write_text("DEPLOY_VERSION: int = 7\n", encoding="utf-8")

    new_version = deployer._increment_deploy_version(tmp_path)

    assert new_version == 8
    assert "DEPLOY_VERSION: int = 8" in version_file.read_text(encoding="utf-8")


@pytest.mark.asyncio
async def test_runtime_contract_smoke_checks_pass_when_probes_match(tmp_path, monkeypatch):
    """Deploy smoke checks should accept healthy mounted app contracts."""
    contracts_path = _write_example_app(tmp_path)
    deployer = LocalDeployer(
        EngineSettings(
            evolved_app_path=tmp_path,
            monitor_url="http://backend:8000",
            runtime_contracts_path=contracts_path,
        )
    )

    async def handler(request: httpx.Request) -> httpx.Response:
        if request.method == "GET" and request.url.path == "/api/v1/apps":
            return httpx.Response(200, json=[])
        if request.method == "POST" and request.url.path == "/api/v1/apps":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/apps/capabilities":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/chat":
            return httpx.Response(422, json={"detail": "missing messages"})
        if request.method == "GET" and request.url.path == "/api/v1/example-app/summary":
            return httpx.Response(
                200,
                json={
                    "total_items": 0,
                    "regions": [],
                },
            )
        if request.method == "POST" and request.url.path == "/api/v1/example-app/items/search":
            return httpx.Response(
                200,
                json={"items": [], "total": 0, "page": 1, "page_size": 25},
            )
        return httpx.Response(404)

    real_async_client = httpx.AsyncClient
    transport = httpx.MockTransport(handler)

    def client_factory(*args, **kwargs):
        kwargs["transport"] = transport
        return real_async_client(*args, **kwargs)

    monkeypatch.setattr(git_ops_module.httpx, "AsyncClient", client_factory)

    ok, message = await deployer._run_runtime_contract_smoke_checks()

    assert ok is True
    assert "Validated 6 runtime contract probes" in message


@pytest.mark.asyncio
async def test_runtime_contract_smoke_checks_fail_on_missing_or_wrong_method(tmp_path, monkeypatch):
    """Deploy smoke checks should fail fast on broken mounted app contracts."""
    contracts_path = _write_example_app(tmp_path)
    deployer = LocalDeployer(
        EngineSettings(
            evolved_app_path=tmp_path,
            monitor_url="http://backend:8000",
            runtime_contracts_path=contracts_path,
        )
    )

    async def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/api/v1/apps":
            return httpx.Response(404, json={"detail": "Not Found"})
        if request.url.path == "/api/v1/apps/capabilities":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "GET" and request.url.path == "/api/v1/example-app/summary":
            return httpx.Response(404, json={"detail": "Not Found"})
        return httpx.Response(200)

    real_async_client = httpx.AsyncClient
    transport = httpx.MockTransport(handler)

    def client_factory(*args, **kwargs):
        kwargs["transport"] = transport
        return real_async_client(*args, **kwargs)

    monkeypatch.setattr(git_ops_module.httpx, "AsyncClient", client_factory)

    ok, message = await deployer._run_runtime_contract_smoke_checks()

    assert ok is False
    assert "GET /api/v1/apps -> HTTP 404" == message


@pytest.mark.asyncio
async def test_runtime_contract_smoke_checks_fail_on_shape_drift(tmp_path, monkeypatch):
    """Deploy smoke checks should reject 200 responses that drift from the JSON contract."""
    contracts_path = _write_example_app(tmp_path)
    deployer = LocalDeployer(
        EngineSettings(
            evolved_app_path=tmp_path,
            monitor_url="http://backend:8000",
            runtime_contracts_path=contracts_path,
        )
    )

    async def handler(request: httpx.Request) -> httpx.Response:
        if request.method == "GET" and request.url.path == "/api/v1/apps":
            return httpx.Response(200, json=[])
        if request.method == "POST" and request.url.path == "/api/v1/apps":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/apps/capabilities":
            return httpx.Response(422, json={"detail": "missing name"})
        if request.method == "POST" and request.url.path == "/api/v1/chat":
            return httpx.Response(422, json={"detail": "missing messages"})
        if request.method == "GET" and request.url.path == "/api/v1/example-app/summary":
            return httpx.Response(
                200,
                json={
                    "total_items": 0,
                    "regions": [],
                },
            )
        if request.method == "POST" and request.url.path == "/api/v1/example-app/items/search":
            return httpx.Response(
                200,
                json={"results": [], "total": 0, "page": 1, "page_size": 25},
            )
        return httpx.Response(404)

    real_async_client = httpx.AsyncClient
    transport = httpx.MockTransport(handler)

    def client_factory(*args, **kwargs):
        kwargs["transport"] = transport
        return real_async_client(*args, **kwargs)

    monkeypatch.setattr(git_ops_module.httpx, "AsyncClient", client_factory)

    ok, message = await deployer._run_runtime_contract_smoke_checks()

    assert ok is False
    assert message == (
        "POST /api/v1/example-app/items/search -> missing JSON fields: items"
    )
